# -*- coding:utf-8 -*-

CONNECTION_PORT = 1000
CONNECTION_ADDRESS = '192.168.0.12'

CONTROLLER_ADDRESS = 2
SOURCE_ADDRESS = 1

COMMAND_LED_CONTROL = 1
FILE_TRANSFER = 2
RGB_CONTROL = 3
COMMAND_TEST = 4

